name: Angular Build Pipeline

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup Node
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. setup packages
      - name: Install dependencies
        run: npm install
        working-directory: PipeLine_Project

      # 4. Run ESLint
      - name: Run ESLint
        run: npm run lint
        working-directory: PipeLine_Project
        
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      # 5. Run Angular tests with coverage
      - name: Run Unit Tests with Coverage
        run: npm run test -- --watch=false --code-coverage
        working-directory: PipeLine_Project

      # 6 Build Angular app
      - name: Build Angular App
        run: npm run build
        working-directory: PipeLine_Project
