name: Angular Build Pipeline

on:
  push:
    branches:
      - main
 


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4
        
       # 2. Install Chrome
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      # 3. Setup Node
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 4. setup packages
      - name: Install dependencies
        run: npm install
        working-directory: PipeLine_Project

      # 5. Run ESLint
      - name: Run ESLint
        run: npm run lint
        working-directory: PipeLine_Project
    
      # 7. Run Angular tests with coverage
      - name: Run Unit Tests with Coverage
        run: npm run test -- --watch=false --code-coverage
        working-directory: PipeLine_Project

      # 8. Login to Docker
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 9. Build Docker Image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/angular-app:latest -f Dockerfile.prod PipeLine_Project
      # 10. Push Docker Image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/angular-app:latest



